### ISSUE TITLE
shouldModuleReload does not receive mapped props from Redux state

### ISSUE THREAD

**Issue by msanfilippof** [americanexpress/holocron#135]
# 🐞 Bug Report

## Describe the bug
`shouldModuleReload` does not receive mapped props from Redux state or any other HoCs.

The current setup of HolocronModule wrapper (internal HoC) does not allow for any additional prop, unless injected from the top.

This makes impossible to reload the module's data with any prop coming from other HoCs.

## To Reproduce
Any root module that need to reload when injected props change (e.g. mapped from Redux state).

## Expected behavior
A root module should be able to inject props to itself via any HoCs and be able to determine its reloading by using such props (e.g. mapped from Redux state).

**Comment by msanfilippof** [comment]
+1

**Comment by JAdshead** [comment]
Thanks for reporting, can you include code examples ?

**Comment by msanfilippof** [comment]
```
MyRoot.holocron = {
  name: 'my-root',
  shouldModuleReload: (prev, next) => prev.aProp !== next.aProp
};

const mapState = (state) => ({
  aProp: state.someProp
})

export default connect(mapState)(MyRoot);
```

**Comment by JAdshead** [comment]
Components further up the render tree are unable to access props injected below. As Holocron will always wrap your modules code it will not run unless that component is forced to rerender, changes in props injected by your `mapStateToProps` will only cause a rerender of components nested below. If you want to force `shouldModuleReload` when your injected props change you will need to do a full rerender of your module.

**Comment by msanfilippof** [comment]
Thanks @JAdshead 

> When possible I would recommend you use loadModuleData only as a function for handling any async tasks required before first render. Ideally it should only ever run the first time the module is rendered.

There are use cases where the root module should reload without losing any cache.

From the docs: https://one-amex-docs.americanexpress.com/en-us/holocron/api/README.md#holocron-module-configuration

NAME | TYPE | REQUIRED | VALUE
-- | -- | -- | --
loadModuleData | ({ store, fetchClient, ownProps, module }) => Promise | false | A function that fetches data required by your module
shouldModuleReload | (oldProps, newProps) => Boolean | false | A function to determine if your loadModuleData and or load function should be called again
mergeProps | (stateProps, dispatchProps, ownProps) => Object | false | Passed down to Redux connect

Seems like it is possible that `loadModuleData` can run again, controlled via `shouldModuleReload`.

Can `mergeProps` be used to inject props above holocron wrapper?

**Comment by msanfilippof** [comment]
I have found that the `route` prop has `store` so I can use `getState` with existing selectors to drive a module reload.
