### ISSUE TITLE
ownProps not passed to loadModuleData on initial server and client renders

### ISSUE THREAD

**Issue by jgolden17** [americanexpress/holocron#38]
# 🐞 Bug Report

## Describe the bug

Two related issues:

When passing props to `RenderModule`, the props are not available to `loadModuleData` during server-side render or during the initial client-side render.  On the second client-side render, the props are available along with `moduleState`.

When passing the same props through `composeModules`, the props are available on the server-side and the initial client-side render.

## To Reproduce

```
const MyModule = () => {
  <div>example</div>
};

MyModule.holocron = {
   name: 'my-module',
   loadModuleData: ({ ownProps }) => {
      console.log('ownProps', ownProps);
      // `ownProps {}` (on server)
      // `ownProps {}` (client initial render)
      // `ownProps { foo: 'foo', moduleState: {...} }`  (client subsequent renders)
  },
};

const RootModule = ({ moduleLoadStatus }) => (
  <React.Fragment>
    {moduleLoadStatus === 'loaded' && (
      <RenderModule moduleName="my-module" props={{ foo: 'foo' }} />
    )}
  </React.Fragment>
);

RootModule.holocron = {
  name: 'root-module',
  loadModuleData: async ({ store: { dispatch } }) => {
    await dispatch(composeModules([{ name: 'my-module' }]));
  },
};
```

## System information

- OS: macOS
- Browser: chrome
- Version of holocron: 1.1.0
- Node version: 12.17.0

**Comment by Francois-Esquire** [comment]
@jgolden17 `composeModules` can take in `[{ name: 'my-module', props: { foo: 'foo' } }]` to pass in `props` on first render and SSR loading. If you'd like, you can also pass `ownProps` from `loadModuleData` to the `compose` fn:

```
RootModule.holocron = {
  name: 'root-module',
  loadModuleData: async ({ store: { dispatch }, ownProps }) => {
    await dispatch(composeModules([{ name: 'my-module', props: ownProps }]));
  },
};
```

**Comment by nellyk** [comment]
@jgolden17  did the solution provided by @Francois-Esquire  resolve the issue

**Comment by JAdshead** [comment]
There is only a single render cycle on the server so loadModuleData is called before render to ensure that any data required is available.

**Comment by nellyk** [comment]
@jgolden17  are you happy for us to close this?

**Comment by jgolden17** [comment]
Yes @nellyk you can close this out

**Comment by nellyk** [comment]
Thank you
