### ISSUE TITLE
Create a pull request template 

### ISSUE THREAD

**Issue by nellyk** [americanexpress/holocron#58]
Create a pull request template
an example can be found at https://github.com/americanexpress/one-app/blob/main/.github/pull_request_template.md

This tutorial can be followed

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by KandyKad** [comment]
Hello, @nellyk can you assign this issue to me please. I'll work on it!!

**Comment by trishkatz** [comment]
@nellyk I can take this one if it's still open.

**Comment by Red-0111** [comment]
@nellyk please assign i will do my best thank you

**Comment by nellyk** [comment]
Assigned to @KandyKad 

@Red-0111  please check if we have any other open issues
