### ISSUE TITLE
If loadModuleData is not passed to Module.holocron, then moduleLoadStatus is always 'loading'

### ISSUE THREAD

**Issue by AdamFoskit** [americanexpress/holocron#63]
# 🐞 Bug Report

## Describe the bug

If neither 'load' nor 'loadModuleData' are passed to [Module].holocron, the module's 'moduleLoadStatus' is 'loading'.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run the one-app generator command: npx -p yo -p @americanexpress/generator-one-app-module -- yo @americanexpress/one-app-module
2. Edit the generated function in the src/components/[name].jsx file to deconstruct 'moduleLoadStatus' from the arguments.
3. Display/console.log the moduleLoadStatus (it will be loading)

## Expected behavior

If there is no asynchronous data to load, 'moduleLoadStatus' should be 'loaded'.

## System information

- OS: Windows (64-bit)
- Browser: N/A
- Version of holocron: ^1.1.0
- Node version: 12.18.1

## Additional context

You can copy/paste this code into the .jsx to easily reproduce:

```javascript
import React from 'react';
import PropTypes from 'prop-types';
import childRoutes from '../childRoutes';

const HelloWorld = ({ moduleLoadStatus }) => {
  if (moduleLoadStatus === 'loading') return <h1>Loading...</h1>; // <-- This will always be returned!
  if (moduleLoadStatus === 'error') return <h1>Error!</h1>;
  return <h1>Hello World!</h1>;
};

HelloWorld.childRoutes = childRoutes;

HelloWorld.propTypes = {
  moduleLoadStatus: PropTypes.oneOf(['loading', 'loaded', 'error']),
};

HelloWorld.holocron = {
  name: 'hello-world',
};

if (!global.BROWSER) {
  // eslint-disable-next-line global-require
  HelloWorld.appConfig = require('../appConfig').default;
}

export default HelloWorld;
```

**Comment by jgolden17** [comment]
Bit of a weird use case but it should probably come in as loaded by default

**Comment by JAdshead** [comment]
So i believe that the issue is in the `componentDidMount` of [holocronModule.jsx](https://github.com/americanexpress/holocron/blob/main/packages/holocron/src/holocronModule.jsx#L112)

```js
componentDidMount() {
  this.mounted = true;
  if (loadModuleData || load) {
    this.initiateLoad(0, this.props);
  }
}
```

the `initiateLoad` function calls `executeLoadingFunctions` which is what sets the state [`status` to `loaded`](https://github.com/americanexpress/holocron/blob/main/packages/holocron/src/holocronModule.jsx#L80) which is then passed to the [`moduleLoadStatus` ](https://github.com/americanexpress/holocron/blob/main/packages/holocron/src/holocronModule.jsx#L150) prop.

**Comment by AdamFoskit** [comment]
@JAdshead It looks like that is the case. The state is initially set to 'loading' [here].(https://github.com/americanexpress/holocron/blob/34b8a998d421453a5fd1d08150c816b0a7f59072/packages/holocron/src/holocronModule.jsx#L105)
