### ISSUE TITLE
Commiting changes from a Windows machine

### ISSUE THREAD

**Issue by AdamFoskit** [americanexpress/holocron#67]
# 💡 Feature request

## Is your feature request related to a problem? Please describe

The test command declared in package.json does not work for Windows' cmd.

## Example
Have a separate test command for Windows machines.

## Describe the solution you'd like
"test:unit": "SET NODE_ENV=development jest"

## Describe alternatives you've considered
The developer could just locally change the command before committing changes or running tests.

**Comment by AdamFoskit** [comment]
Maybe [cross-env](https://www.npmjs.com/package/cross-env) would be a good library for this.

**Comment by nellyk** [comment]
Thank you for your contribution
